added basic float and int vector type structs and math module
SapphireNick/Shadowheart pull request #14
Opened 2021-03-26 06:42 UTC by d-jakob

Closing #7

2021-03-26 06:45 UTC, d-jakob commented
how do we want functions returning a reference formatted? I prefer grouping the & with the type in this case

2021-03-26 10:31 UTC, SapphireNick requested changes
Too much overhead for what just are aliases for existing, basic data-types.

2021-03-26 10:31 UTC, SapphireNick commented on modules/math/include/m_vec.hh
> +struct vec1 {
This really should just be `using vec1 = float`. We dont need to overload operators and make a whole struct for what just is one float. The OpenGL functions do also only expect floats/ints etc. in cases where vec1 are used.

2021-03-26 10:31 UTC, SapphireNick commented on modules/math/include/m_vec.hh
> +struct ivec1 {
Same as for vec1 only now `using ivec1 = int`

2021-03-26 10:31 UTC, SapphireNick commented on modules/math/src/m_vec.cc
> +float& Shadowheart::Math::vec1::operator[](const int &i) { return _v[i]; }
Should not be needed if comments in m_vec.hh are adressed.

2021-03-26 10:31 UTC, SapphireNick commented on modules/math/src/m_vec.cc
> +int& Shadowheart::Math::ivec1::operator[](const int &i) { return _v[i]; }
Should not be needed again.

2021-03-26 10:33 UTC, SapphireNick commented
> how do we want functions returning a reference formatted? I prefer grouping the & with the type in this case

Agreed. Will (try) to configure our .clang-format when the time for formatting comes for this pr.

2021-03-27 14:05 UTC, SapphireNick commented
> > how do we want functions returning a reference formatted? I prefer grouping the & with the type in this case
> 
> Agreed. Will (try) to configure our .clang-format when the time for formatting comes for this pr.

I don't think this is going to work quite like we want it to work...

2021-03-29 11:55 UTC, SapphireNick approved these changes
LGTM !

2021-03-29 11:56 UTC, SapphireNick commented
I'm going to run it through the formatting and merge it.

2021-03-29 12:03 UTC, merged