Added convenience functions for Uniforms
SapphireNick/Shadowheart pull request #21
Opened 2021-03-29 15:02 UTC by SapphireNick

Done all functions for int and float vectors.

Closing #5

2021-03-29 15:03 UTC, SapphireNick commented
I realized in #20 the math-module, you @d-jakob wrapped the functions in the source file in namespaces again yet i didn't. Both work and both would work without them. How should we do it?

2021-03-30 13:59 UTC, d-jakob requested changes
I think wrapping them in the namespaces again improves readability as it will make it possible to remove the `Shadowheart::Renderer::` from every function

2021-03-30 13:59 UTC, d-jakob commented on modules/renderer/src/r_shader.cc
> +}
I thought we are using 
```
rtype fname(params)
{
  code
}
```
?

2021-03-30 15:03 UTC, SapphireNick commented
> I think wrapping them in the namespaces again improves readability as it will make it possible to remove the `Shadowheart::Renderer::` from every function

Noted. Will change this.

2021-04-01 09:30 UTC, SapphireNick commented on modules/renderer/src/r_shader.cc
> +}
Well the newlines do not show, oh well..

2021-04-05 11:47 UTC, d-jakob approved these changes
I added the lf at eof myself this time

2021-04-05 11:47 UTC, merged

2021-04-05 11:47 UTC, SapphireNick commented
Thank you !