Finished implementing entry point structure
SapphireNick/Shadowheart pull request #25
Opened 2021-03-30 12:26 UTC by SapphireNick

The main.cc in the root folder is, for now, to keep track of how the user experience should look like and simultaneously keep track of the current ux structure.

Closes #22

2021-03-30 14:08 UTC, d-jakob requested changes
Also we agreed on an indentation level of 2 spaces instead of the 4 in all of the files in this pr, right?

2021-03-30 14:08 UTC, d-jakob commented on include/Shadowheart.hh
> +#endif // SHADOWHEART_HH
no newline at the end of file

2021-03-30 14:08 UTC, d-jakob commented on main.cc
> +}
no newline at the end of file

2021-03-30 14:08 UTC, d-jakob commented on main.cc
> +}
function style see #21 ?

2021-03-30 14:08 UTC, d-jakob commented on src/Shadowheart.cc
> +}
newline again

2021-03-30 15:01 UTC, SapphireNick commented on include/Shadowheart.hh
> +#endif // SHADOWHEART_HH
As said in my comment, formatting issues will be taken care of after review and before merging.

2021-04-01 09:40 UTC, SapphireNick commented
Fixed formatting. The main.cc is again only to test and see, if the implementation of the entry point works as we anticipate. It is not a main part of the project.

2021-04-05 11:42 UTC, d-jakob approved these changes

2021-04-05 11:43 UTC, merged